[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1nbp3cLjXhAZCIxvt22GVjUeK687vpTb34HZA1XXDaRs/edit?usp=sharing"
type = "service_account"
project_id = "gogole-sheet-484314"
private_key_id = "47c5737b038817b9662ec7e260fe47bfdefe298c"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDhwm+omDtRWuRX
cl8ImGP16wOkX/JkiFmomX/wCTPHSNzhdP9/kMNgWUh2AsrnNjrxt1BCefJmbPHH
gBBsuwIAaDoMwsyAcg162HJ1+3/alPSABNEyl6RV9usV50vK+ryCyhfPiz7dmrmC
1AqPPvpJQFdy/e1jl5XFRw1qolRl42nUiLWNhDvo+mWD54jqfdT7MUVwqc70xUIQ
hy39MzdBg2mf62lGfrkABF6qp8vYL/EIVHvSkvwok8jPo926HZr0TEnywK/wPAhd
PjD2mgLnwuhnX7PzJGj1Imm72s8T+/mm1ybmPcjakSalqm/KLz8m679Kn/9/cIu5
GbVaJruNAgMBAAECggEAPcGJ+NUX2OPjtbYgIAJLyeAtgWALtwuDdzbyQ+/IfbnF
TllKcRNhFrClvT57Ua9IhYmvR1gDgphHtVqnY47ud70LMCVzeql4XYPrH7IaIemA
TqrCrTPFLQzb9wRr+80GF0MAK3J8UnN6TrsBXnkMT1Bt+5NRxl4Xhr0ugt5/9tSw
tsQ/AbbKS3Z+0Feqwkt4UBngdSRju76DypB+EjqVytcZ5roPraM0lqPacJV1c3BQ
go92zlsW910Wk3+TwqfZXedIG6Sn70WXL3MCn0dXuW5QjrU17y7Osp/1kkiIP4kH
wWOV1U38At82iH9S/QpEn7IVJpZdZG1J+7Ihz4ifswKBgQD1iTQfDH53DHK4FsXV
hhZ4Ig5GOG5mDm6lzVvj4xidvdgINn+YsTyULbdu+vszCsfflOFghFX/OM4cZKm/
Qj45Dql31aMd6+mvLWjH7I9WPn50TWrG30szF/Ktnw5hPxNvs9mfrS2ObmDADaqw
CFmhq1mY8dAs7lBBLOIbNSRRAwKBgQDrYXjDAA7X+KSEwLYSqsrel8aQORV6OBuS
AFJUDUHN7Aqk80VpKMFk/VymZXiTRw8Xg7bxyF/TdGMmvKQCLUCTvnUaoJepOPTY
Y+M7aU1lgFkm9Gz+x16xJFcUb7SJ4EkLWJ8bf4WwVvAHcA2xg9tRTQJE8/8jg7qp
4STwPBf0LwKBgQC9YRnmaMiSIfPJsSbdzhI+jmXcG2JrLO6Cy6X4Wwx9fhPGIeLA
btN+ptQ4sTRW5hXLiRVcUDXUKIgwtiOG9Rzw/TIQz6KETZVsG+YZbYgQyRrXsW6N
/WQPAIWZDHkW4IOpQFq2IehlVxUgjGn+ZDJd07/Di585SIZ1/pxWx+I+6QKBgQDa
duZZvsUIKOuxlxembcTLIn2WQJUxkb/tG8VN49wOnyUmAfCLcNtGu21xtz5ZG5vj
TEnRURO3tA+O1Yk3x/5m4l/YLfN1ibqe2N7/tnWyXpTgdf5v3mWB7mOwQRmE2pmR
IVjTceGIULiJfrQG7YXyiJIxo3FL6iinIaNiIbRt2wKBgQCIUZ7aLSsfiuHlYWQx
kIgcBdp4XuF9mYpiaKh4aY7hq0BSmQC8VcGQH4uSUCvzMT7guNzuj45VaZrzBw49
5W938eMtt7CgUSeNIrSu9ik9onWDWgssLSYYunekw7dNIyEB/08ooxXcW5gdaF+o
tYMcRYKKzoqOVeBpN3/fknmBUg==
-----END PRIVATE KEY-----
"""
client_email = "inverter@gogole-sheet-484314.iam.gserviceaccount.com"
client_id = "102262259427022989838"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/inverter%40gogole-sheet-484314.iam.gserviceaccount.com"
